# docker-compose.yml

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: habiliai
      POSTGRES_USER: habiliai
      POSTGRES_PASSWORD: habiliai
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    configs:
      - source: init.sql
        target: /docker-entrypoint-initdb.d/init.sql
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  habapi:
    build:
      dockerfile: ./api/Dockerfile
    command:
      - sh
      - -ce
      - |
        ./habapi seed --reset
        ./habapi serve
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      includeDebug: true
      db.user: habiliai
      db.password: habiliai
      db.name: habiliai
      db.host: localhost
      db.port: 5432
      openai.apiKey: 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
    depends_on:
      - postgres
    restart: always

configs:
  init.sql:
    content: |
      CREATE DATABASE test WITH OWNER = habiliai;

volumes:
  minio_data: